/** Story copy. Homepage lines are the bet 7 pass. Dig lines stay as shipped. */

export const STORY = {
  landEyebrow: 'Unbranded',
  landTitle: 'Do you show up for what you solve?',
  landHelper: "Questions are generated based on your brand's website",
  landBadge: 'Unbranded',
  ask: 'Ask about your brand',
  digLoading: 'Checking what they say when people name you…',
  digEyebrow: 'Branded',
  digTitle: 'What do they say about you?',
  digHelper: 'Questions that name your brand — tone, claims, how you’re described.',
  digBadge: 'Branded',
  digFail: 'Couldn’t generate branded questions — try again.',
  answerLabel: 'Generated · OpenAI',
  answerHelper:
    'Answers below are from our model for these questions — not a live multi-engine scrape.',
  answerMiss: 'Couldn’t get an answer.',
  documentTitle: 'Grank — See if you show up in AI answers',
  headerBadge: 'SIMPLE AEO · LABELED MODEL CHECKS',
  homeH1: 'What does AI say about your brand?',
  homeSub: 'See what LLMs say when your audience asks about the problems you solve.',
  urlPlaceholder: 'https://yourbrand.com',
  cta: 'Check visibility',
  homeLoading: 'Checking how AI might talk about you…',
  exampleLead: 'Or try an example:',
  homeProof:
    'We generate questions and answers with OpenAI and label every block. This is not a live multi-engine scrape — and we never blend branded + unbranded into one score.',
  foilTitle: 'Built for thin teams',
  foilBody:
    '“Are we in AI answers?” shouldn’t need a $499 demo or a prompt lab. Suites sell ops. You need a glance: do you show up for what you solve — and who shows up instead.',
  foilFoot:
    'Land on unbranded. Dig into branded when you’re ready. Free checks, then one simple upgrade if you need more — no credit packs.',
  deltaTitle: 'What’s changed',
  deltaHelper: 'A short read on this check since the previous run.',
  deltaAwaiting: 'Run again to start comparing over time.',
  deltaEmpty: 'No mention changes since the previous run.',
  deltaNewlyMentioned: 'Newly mentioned',
  deltaLostMention: 'Lost mention',
  deltaNowMentioned: 'Now mentioned',
  deltaWhoAppeared: 'Newly showing up instead',
  deltaWhoDropped: 'No longer showing up instead',
  overTimeTitle: 'Over time',
  overTimeHelper: 'Each column is one run. Same questions — mention status as you re-run.',
  overTimeQuestion: 'Question',
  overTimeLegend: 'Mentioned · Not mentioned · Unclear',
  themeMentionRate: '{pct}% mentioned',
  themeMentionRow: '% mentioned',
  themeMentionCell: '{pct}%',
  themeAcrossRuns: 'Across runs: {a}% → {b}%',
  manageQuestionsCta: 'Manage questions',
  manageQuestionsTitle: 'Manage questions',
  manageQuestionsHint: 'Add, remove, or rename questions for this check. Save, then Run again.',
  whoInsteadBoardTitle: 'Who showed up instead',
  whoInsteadBoardHelper: 'By topic, on unbranded questions this run — not market share.',
  whoInsteadBoardEmpty: 'No one else showed up yet.',
  whoInsteadBoardCount: 'Appeared on {n} questions',
  whoInsteadBoardMore: '{n} more in the questions',
} as const
